import React from 'react';
import { render } from 'react-dom';
import {Button,Row,Col,Icon, message} from 'antd';
import {EasyComponent,createVirtualDomId,createElementId} from '../../src';
import '../../src/less/index.less';
// import '../../es/less/index.less';
// import '../../dist/index.css';
const defaultVirtualDomData = [{
  id:createVirtualDomId(),
  type:'div',
  canDrop:true,
  style:{
    padding:'10px'
  },
  children:[{
    id:createVirtualDomId(),
    type:'div',
    canDrop:true,
    props:{
      className:'table-wrapper',
    },
    style:{
      color:'red',
      padding:'10px'
    },
    children:[{
      id:createVirtualDomId(),
      type:Button,
      props:{
        type:'primary',
        icon:'search'
      },
      children:'点击'
    },{
      id:createVirtualDomId(),
      type:Button,
      style:{
        marginLeft:'10px'
      },
      children:'hello'
    }]
  },{
    id:createVirtualDomId(),
    type:Row,
    style:{
      paddingTop:'10px',
      paddingRight:'20px',
      paddingBottom:'10px',
      paddingLeft:'10px'
    },
    children:[{
      id:createVirtualDomId(),
      type:Col,
      canDrop:true,
      canDrag:false,
      props:{
        span:4
      },
      style:{
        padding:'10px'
      },
      _style:{
        minHeight:'80px'
      },
      children:[{
        id:createVirtualDomId(),
        type:Icon,
        props:{
          type:'caret-left'
        }
      }]
    },{
      id:createVirtualDomId(),
      type:Col,
      canDrop:true,
      canDrag:false,
      props:{
        span:4
      },
      _style:{
        minHeight:'80px'
      },
    }]
  }]
}];
const elements = [{
  groupName:'按钮',
  elements:[{
    id:createElementId(),
    name:'主要按钮',
    image:'https://ss2.baidu.com/6ONYsjip0QIZ8tyhnq/it/u=2153073326,2406502881&fm=58&s=D2C7D812C0B12D800C1BB1CD0300F0A9&bpow=121&bpoh=75',
    virtualDomData:{
      type:Button,
      props:{
        type:'primary'
      },
      children:'主要按钮'
    }
  },{
    id:createElementId(),
    name:'次要按钮',
    image:'https://ss2.baidu.com/6ONYsjip0QIZ8tyhnq/it/u=2153073326,2406502881&fm=58&s=D2C7D812C0B12D800C1BB1CD0300F0A9&bpow=121&bpoh=75',
    virtualDomData:{
      type:Button,
      props:{
        type:'info'
      },
      children:'次要按钮'
    }
  }]
},{
  groupName:'栅格',
  elements:[{
    id:createElementId(),
    name:'二分之一',
    image:'https://ss2.baidu.com/6ONYsjip0QIZ8tyhnq/it/u=2153073326,2406502881&fm=58&s=D2C7D812C0B12D800C1BB1CD0300F0A9&bpow=121&bpoh=75',
    virtualDomData:{
      type:Row,
      children:[{
        type:Col,
        props:{
          span:12
        },
        _style:{
          minHeight:'80px'
        },
        canDrop:true
      },{
        type:Col,
        props:{
          span:12
        },
        _style:{
          minHeight:'80px'
        },
        canDrop:true
      }]
    }
  }]
}];
render(<EasyComponent defaultVirtualDomData={defaultVirtualDomData} elements={elements} onSave={()=>{message.success('保存成功')}}/>, document.getElementById('root'))
